[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
cli-table = "0.5.0"
inventory = "0.3.21"
seq-macro = "0.3.6"
